---
- name: installing httpd server
  hosts: webserver
  become: True
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: installed
    - name: starting service
      service:
        name: httpd
        state: started
